### ISSUE TITLE
No AF output and DP output 

### ISSUE THREAD

**Issue by lidd77** [MGHComputationalPathology/CellTics#5]
HI,
 I test this script  using my valited sample,  there is no AF and DP output of  the merged site .
Is a bug for CellTics ?

**Comment by alliemacleay** [comment]
It wasn't a bug really.  I hadn't added the functionality but I should.  Thanks for your input.

**Comment by alliemacleay** [comment]
Actually I looked closer and it is using ALT_AF and ALT_DP fields for the allele fraction and depth.  It's averaging the ALT_AF and ALT_DP values of all the variants, which isn't really correct, but there's a question of how to handle merged regions having different depths.  Also, this tool will chain variants so that the first and last may not necessarily appear on the same read if there are others in between that link them.  I'm not sure what the correct strategy is to aggregate these.
