### ISSUE TITLE
Wrong WARNING message?

### ISSUE THREAD

**Issue by pieterlukasse** [MGHComputationalPathology/CellTics#8]
when I run 

```
docker run --rm \
> -v $PWD/tests/vargroup_in.vcf:/input_file.vcf:ro \
> -v /tmp/vargroup_output:/tmp/vargroup_output:rw \
> -v $PWD/tests/refs_folder/mini_genome.fasta:/hg19.fasta:ro \
> vega_celltics \
> celltics vargroup \
>     -i /input_file.vcf \
>     -o /tmp/vargroup_output/output_file.vcf \
>     --ref-seq /hg19.fasta \
>     --merge-distance 30 -t 1  -w "merged_only"
```
I get the warning: `WARNING:  builtins: This module cannot be called using the cli library. Multiprocessing does not work because of dependency on the pickle library.  Classes created at the interpreter level cannot be pickled. ` 

From the documentation I thought the option `-t 1` would suppress this warning? Did I miss something or is this a bug?

The rest of the output is:
```
Grouping file: /input_file.vcf
0 seconds to process with 1 threads
Found 1 variants to merge
Rejected groups: 0
```

**Comment by alliemacleay** [comment]
This should be called with python.  The call did work because you did not use multiprocessing but it isn't meant to be called through the cli library.  You can ignore the error.  I will leave it there for now because it should not be called this way generally.

**Comment by pieterlukasse** [comment]
hm...this is what I read in the documentation:
```
...
VarGrouper runs multithreaded by default. Use --debug or set threads to 1 (-t 1) to avoid multiprocessing.

### Simplest vargroup command
celltics vargroup --input-file sorted_variants.vcf 
--output-file grouped_variants.vcf --ref-seq hg19.fasta -t 1
```
Is the documentation wrong?

**Comment by alliemacleay** [comment]
You're right, the documentation should be updated.  

Your process completed and did not run with multithreading.  The warning is shown regardless of the parameters.

```
if __name__ == '__main__':
    cli()
elif not __name__.startswith('celltics'):
    print('WARNING:  {}: This module cannot be called using the cli library.\n'
          'Multiprocessing does not work because of dependency on the pickle library.  Classes created at the '
          'interpreter level cannot be pickled.\n'.format(__name__))```

I expected to invoke this with the cli() library but found that multiprocessing does not work when invoked by "celltics vargrouper".  The parameters have not been evaluated at the level at which I show the warning.  I think it is still useful to have it shown because the intended usage is not to invoke it with "celltics vargrouper" but with "python celltics/tools/vargrouper.py".  I also would have to do a lot of work to find out if there's a way to access the parameters before they are passed into the cli function.

Refactoring this project to not use cli() is another option.  I expected there would be more tools developed for this project and the cli library is commonly used in other software in MGH CompPath.

**Comment by pieterlukasse** [comment]
thanks @alliemclean . I would vote for having just one way of calling it and keeping only that in the documentation. For now, I have adjusted my scripts to call `vargroup.py` directly.

**Comment by alliemclean** [comment]
I agree.  I'm not in charge of this project now but I'll leave it to them to decide whether refactoring this is a priority (@llipkinMGH).  I hope the README makes more sense.  Thanks for your feedback!  I'm closing this issue.
